name: Deploy to Server

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/repos/AberdeenRSS/FlightManagementServer
            git checkout main
            git pull
            sudo -n /usr/bin/docker build . -t flight-management-server:latest
            cd /usr/share/uoarocketry-docker/docker
            sudo -n /usr/bin/docker-compose stop
            sudo -n /usr/bin/docker-compose up -d
