name: Run Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
    
jobs:
    test:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [3.11.9]

        services:
            mongodb:
                image: mongo:latest
                ports:
                    - 27017:27017
                options: --health-cmd "exit 0"
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Python
              uses: actions/setup-python@v3
              with:
                python-version: 3.11.9
            - name: Install Dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Generate PEM files for tests
              run: |
                openssl genrsa -out private.pem 2048
                openssl rsa -in private.pem -pubout -out public.pem
            - name: Run Tests
              run: |
                pytest